name: ci

on:
  push:
    branches:
      - "v2"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "uyorum/mirakurun-epgstation"
          install: true
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "./epgstation"
          file: "./epgstation/debian.Dockerfile"
          tags: "uyorum/rpi-mirakurun-epgstation"
          platforms: linux/arm/v7
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}
